name: reviewdog
on: 
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Install shellcheck
          run: |
            sudo apt install shellcheck
        - name: Install reviewdog
          run: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
        - name: Run Reviewdog
          env:
            REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REVIEWDOG_FAIL_ON_ERROR: 'true'
          run: |
            mkdir -p "$PWD"/scan_results
            ./bin/reviewdog -conf .github/.reviewdogConfig.yml -reporter=github-pr-check
        - uses: actions/upload-artifact@v3
          with:
            name: scan_results
            path: ${{ github.workspace }}/scan_results/
            

        
        
